name: app-quality-check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./src/code-templates

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # Uncomment and replace with current `os` when windows-run bug is fixed
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install root dependencies
        run: npm i

      - name: Install granular dependencies
        run: npx turbo run installDependencies

      - name: Test
        run: npx turbo run test
