name: practica-quality-check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [main]

jobs:
  strategy:
      matrix:
        node-version: [10.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest]

  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: npm ci
      - run: npm test 
